### ISSUE TITLE
NSwag generation for b2b schema

### ISSUE THREAD

**Issue by absinghal** [ONDC-Official/ONDC-RET-Specifications#97]
Using NSwag to generate code from https://github.com/ONDC-Official/ONDC-RET-Specifications/blob/master/api/build/build.yaml

It gives an error  Could not resolve the path '#/paths/~1init/post/responses/default'.

Perhaps the defaultresponse ref needs to be added as a component.

PL advise

Thanks

**Comment by tanyamadaan** [comment]
Kindly refer to release-2.0.2 branch - https://github.com/ONDC-Official/ONDC-RET-Specifications/tree/release-2.0.2

**Comment by absinghal** [comment]
Thanks, it seems the issue is with NSwagStudio, and works fine with SwaggerHub.
